name: Deploy Infrastructure to AWS

on:
    push:
        branches:
            - main

jobs:
    tf_fmt:
        name: Deploy Site
        runs-on: ubuntu-latest
        steps:

        - name: Checkout Repo
          uses: actions/checkout@v1


        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.9.3

        - name: Terraform Initialization
          uses: hashicorp/terraform-github-actions/init@v0.4.0

          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
            TF_ACTION_WORKING_DIR: 'terraform'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
        - name: Terraform Validation
          uses: hashicorp/terraform-github-actions/validate@v0.3.7


        - name: Terraform Apply
          uses: hashicorp/terraform-github-actions/apply@v0.4.0
          
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
            TF_ACTION_WORKING_DIR: 'terraform'
            AWS_REGION: 'us-west-2'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        

        - name: Deploy to S3 bucket
          uses: jakejarvis/s3-sync-action@master

          env:
            SOURCE_DIR: './website'
            AWS_REGION: 'us-west-2'
            AWS_S3_BUCKET: 'myterraformprojectwebsite20011231'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            