name: Deploy Infrastructure to AWS

on:
    push:
        branches:
            - main

jobs:
    tf_fmt:
        name: Deploy Site
        runs-on: ubuntu-latest
        steps:

        - name: Checkout Repository
          uses: actions/checkout@v1


        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.9.3
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            aws-region: us-west-2
        
        - name: List files
          run: ls -R
          working-directory: terraform

        - name: Terraform Initialization
          run: terraform init
          working-directory: terraform
    
        - name: Terraform Validate
          run: terraform validate
          working-directory: terraform
    
        - name: Terraform Apply
          run: terraform apply -auto-approve
          working-directory: terraform
          

        - name: Deploy to S3 bucket
          uses: jakejarvis/s3-sync-action@master

          env:
            SOURCE_DIR: './website'
            AWS_REGION: 'us-west-2'
            AWS_S3_BUCKET: 'myterraformprojectwebsite20011231'
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            